### ISSUE TITLE
conf/waf/init.lua:170: bad argu    ment #1 to 'pairs' (table expected, got nil)

### ISSUE THREAD

**Issue by aa1215018028** [unixhot/waf#11]
为什么按照说明的操作提示这个错误，init_lua 第170行pairs的参数为空。
2017/09/11 20:29:28 [debug] 14548#0: *23152 regex "/(attachments|upimg|images|css|uploadfiles|html|uploads|templets|static|template|data|in    c|forumdata|upload|includes|cache|avatar)/(\\w+).(php|jsp)" not matched on string "/testhello" starting from 0
157 2017/09/11 20:29:28 [debug] 14548#0: *23152 lua resume returned 2
158 2017/09/11 20:29:28 [error] 14548#0: *23152 lua entry thread aborted: runtime error: /liyang/openresty-test/conf/waf/init.lua:170: bad argu    ment #1 to 'pairs' (table expected, got nil)

**Comment by MrYuanZhen** [comment]
报错已经很明显了,应该是作者写错了,post那一段修改成
`function post_attack_check()
    if config_post_check == "on" then
        local POST_RULES = get_rule('post.rule')
        for _,rule in pairs(POST_RULES) do
            ngx.req.read_body()
            local POST_ARGS = ngx.req.get_post_args()
        end
        return true
    end
    return false
end
`
