### ISSUE TITLE
请问下您有没有用过modsecurity；如果都用modsecurity的secRule可以做到这些功能吗

### ISSUE THREAD

**Issue by ghost** [unixhot/waf#13]
就是在 `nginx+modsecurity`的基础上直接开发; 能不能达到您这个效果; 如果可以，思路又是怎么样的。

**Comment by unixhot** [comment]
您好，是这样的。modsecurity非常不错，但是Modsecurity的Nginx模块性能是一个大问题。但是
Modsecurity的规则是一个财富，可以借鉴，甚至直接照搬过来。

2018-05-21 15:11 GMT+08:00 actanble <notifications@github.com>:

**Comment by actanble** [comment]
非常感谢您的回答
