### ISSUE TITLE
竟然一个问题没有，最近我在测试ngx_lua_waf，日志分析确实很重要。

### ISSUE THREAD

**Issue by minminmsn** [unixhot/waf#2]
竟然一个问题没有，最近我在测试ngx_lua_waf，看到这个我打算再测试下这个，看看这两个到底有什么区别，目前ngx_lua_waf日志格式不是json的，费了九牛二虎之力才用grok切分得马马虎虎，能在ELK上展示了。

**Comment by unixhot** [comment]
我这里已经修改为json了。可以直接使用codec=>json进行收集的。
