### ISSUE TITLE
使用openresty/openresty:alpine镜像集成waf后启动报错

### ISSUE THREAD

**Issue by Think-Me** [unixhot/waf#23]
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file '/usr/local/openresty/nginx/conf/resty/core.lua'
        no file '/usr/local/openresty/site/lualib/resty/core.so'
        no file '/usr/local/openresty/lualib/resty/core.so'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by huanhaixy** [comment]
我解决方法是去除nginx配置里边的 lua_package_path ，waf 文件放到/usr/local/openresty/site/lualib。修改config.lua 中的路径配置。

**Comment by yujunhui** [comment]
将
`lua_package_path "/usr/local/openresty/nginx/conf/waf/?.lua";`
改成
`lua_package_path "/usr/local/openresty/nginx/conf/waf/?.lua;;";`

末尾两个分号是指新加的路径后面加上原来的默认路径。

**Comment by unixhot** [comment]
可以增加一个软链接 ln -s /usr/local/openresty/lualib/resty/ /usr/local/openresty/nginx/conf/waf/resty
