### ISSUE TITLE
去掉access.lua里面被注释的代码后报错了

### ISSUE THREAD

**Issue by huangbenq** [unixhot/waf#26]
`require 'init'

function waf_main()
    if white_ip_check() then
    elseif black_ip_check() then
    elseif user_agent_attack_check() then
    elseif cc_attack_check() then
    elseif cookie_attack_check() then
    elseif white_url_check() then
    elseif url_attack_check() then
    elseif url_args_attack_check() then
    elseif post_attack_check() then
    else
        return
    end
end

waf_main()

`

错误日志

> 2020/01/07 18:15:53 [error] 165#0: *40 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/conf/myconf/waf/init.lua:170: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/usr/local/openresty/nginx/conf/myconf/waf/init.lua:170: in function 'post_attack_check'
	/usr/local/openresty/nginx/conf/myconf/waf/access.lua:12: in function 'waf_main'
	/usr/local/openresty/nginx/conf/myconf/waf/access.lua:18: in main chunk, client: 10.211.55.2, server: localhost, request: "GET /abcdef/core/notification/count.do HTTP/1.1", host: "10.211.55.9", referrer: "http://10.211.55.9/abcdef/index.do"

**Comment by hlpureboy** [comment]
因为post的那个检测的地方没写

**Comment by unixhot** [comment]
是的，那个没有完成，近期开始准备继续。
