### ISSUE TITLE
我多域名配置时，waf_logs里面server_name只记录了第一个域名

### ISSUE THREAD

**Issue by minminmsn** [unixhot/waf#3]
我conf文件server_name行配置多域名时，waf_logs里面只记录了第一个域名，其他域名记录不了，不知道是什么原因？

**Comment by minminmsn** [comment]
后来lib.lua改成 local SERVER_NAME = ngx.var.host解决了。

**Comment by unixhot** [comment]
好的，谢谢分享。

2016-09-08 11:46 GMT+08:00 Jerry Min <notifications@github.com>:
