### ISSUE TITLE
按照文档配置，lua模块报错，不知道是不是代码的问题。

### ISSUE THREAD

**Issue by Sirius2016** [unixhot/waf#8]
2017/08/02 19:29:01 [error] 18148#0: *14 lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/init.
lua:152: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/usr/local/nginx/conf/waf/init.lua:152: in function 'user_agent_attack_check'
	/usr/local/nginx/conf/waf/access.lua:6: in function 'waf_main'
	/usr/local/nginx/conf/waf/access.lua:18: in function </usr/local/nginx/conf/waf/access.lua:1>, client: 12
5.39.239.6, server: localhost, request: "GET //index.php/api/index/imgcode HTTP/1.1", host: "gd.lo-x.cc", referre
r: "http://www.baidu.com/s?wd=www"

**Comment by Sirius2016** [comment]
请大神帮忙解答一下，谢谢。
急，在线等

**Comment by Sirius2016** [comment]
貌似是说init.lua这个文件152行报错。
lua entry thread aborted: runtime error: /usr/local/nginx/conf/waf/init.
lua:152: bad argument #1 to 'pairs' (table expected, got nil)

**Comment by unixhot** [comment]
只能说和版本有关系？根据文档安装确认没有问题。你有调整过其它东西吗。

2017-08-02 19:44 GMT+08:00 Sirius2016 <notifications@github.com>:

**Comment by Sirius2016** [comment]
应该是版本问题。安装新版问题解决了。谢谢

**Comment by onlyFarmer** [comment]
> 应该是版本问题。安装新版问题解决了。谢谢

哪个安装新版？

**Comment by Sirius2016** [comment]
把openresty升级一下，就解决了。

**Comment by LikeLifeNNB** [comment]
openresty升级到几?
